package br.com.cascao.realmofcard.enumerator;


public enum StatusPedidoEnum{
    PAGAMENTO_PENDENTE_DE_APROVACAO,
    PAGAMENTO_NEGADO,
    PAGAMENTO_PROCESSADO,
    PEDIDO_RECUSADO,
    EM_TRANSPORTE,
    ENTREGUE,
    TROCA_PENDETENTE_DE_APROVACAO,
    TROCA_RECUSADA,
    AGUARDANDO_RECEBIMENTO_DO_PRODUTO,
    TROCA_FINALIZADA
}